### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cjbarth**
Simple update to the README file to express the new intent of this library.

### CODE REVIEW

**Comment by kriss1897** [comment]
@cjbarth Is this the final version for this PR? Or are you going to update other parts of README as well?

**Comment by cjbarth** [comment]
I'm only updating this one part for now. I have no need for a separate SAML library, `passport-saml` suites me just fine. However, I'll continue helping shepherd the split along. I just wanted the README to correctly reflect why this repo exists and the direction it was going. I expect that as others make changes the README will have to be updated.

**Review by cjbarth — COMMENTED** [review]
These changes look good to me. However, with some new branch rules I've turned on and am trying to follow myself, I can't approve my own branch :)

**Review by zoellner — APPROVED** [review]
lgtm

**Review by zoellner — APPROVED** [review]

**Pull request merged**
