### PR TITLE
Add test coverage for initialize() of saml.ts

### PR DESCRIPTION
**Pull request by kg0r0**
# Description

I worked on some of the issue https://github.com/node-saml/node-saml/issues/70 .
Perhaps this issue could be addressed in stages.

# Checklist:

- Issue Addressed: [x]
- Link to SAML spec: N/A
- Tests included? [x]
- Documentation updated? N/A

### CODE REVIEW

**Comment by cjbarth** [comment]
Thank you very much for contributing this. Can you please address the problems with linting?

**Comment by kg0r0** [comment]
> Thank you very much for contributing this. Can you please address the problems with linting?

Hi @cjbarth,
Sorry I did not notice the eslint error.

It seems that this repository allows the use of  ``// eslint-disable-next-line @typescript-eslint/no-explicit-any ``. Is this correct?

https://github.com/node-saml/node-saml/blob/cbe102ab99346f5282dfb2ab629d1ffac6504c6f/src/types.ts#L45-L46

I think sometimes it is necessary to pass a type check in order to test every exceptions, and a type assertion using any is used for this purpose.
If the above is ok, I can rebase and push the changes again to wrap up the commits.

**Comment by cjbarth** [comment]
For test especially, that is true. Did you try `unknown`?

**Comment by kg0r0** [comment]
> For test especially, that is true. Did you try `unknown`?

Okay, this is test code so I will push that change.
I also tried `unknown` but this did not seem to work.

```
Argument of type 'unknown' is not assignable to parameter of type 'SamlConfig'.
  Type 'unknown' is not assignable to type 'Partial<SamlOptions>'.ts(2345)
```

**Comment by cjbarth** [comment]
Ok, then put in the comment :)

**Review by cjbarth — APPROVED** [review]

**Pull request merged**
