### PR TITLE
V4.0.0 beta.3

### PR DESCRIPTION
**Pull request by yubing24**
# Description

Updated `xml-encryption` to version `2.0.0`.  `xml-encryption` version 2.0.0 contains a security patch to update the vulnerable version of `node-forge` (see https://github.com/auth0/node-xml-encryption/releases/tag/v2.0.0).

# Checklist:

- Issue Addressed: [ ]
- Link to SAML spec: [ ]
- Tests included? [ ]
- Documentation updated? [ ]

### CODE REVIEW

**Comment by cjbarth** [comment]
The `master` branch is already on v2.0.0. See https://github.com/node-saml/node-saml/blob/3d61e918b272a6bf32872b7b266c1244f9c4a87a/package.json#L63

**Comment by yubing24** [comment]
Thanks. My organization's project is using the tag release 4.0.0-beta.2, which is using the vulnerable version of `xml-encryption`, I thought bumping the version of `xml-encryption` would be the proper solution here. 
Is the master branch on release v3.0.0? I tried downgrading project to v3 but tests started breaking. Is there any breaking change between v4 and v3? Thanks!

**Comment by cjbarth** [comment]
@yubing24 be careful. We recently discovered a vulnerability in that beta version: https://github.com/node-saml/node-saml/issues/82.

**Comment by srd90** [comment]
@yubing24 this repository's master branch'es version number is not updated for ages. It is still 3.0.0 even though there has been 3 beta releases. It seems that @zoellner (who is only one who has privileges to publish to npmjs's node-saml repository) has created those beta releases from some other branches and master branch'es version number has not been updated (btw. node-saml/node-saml repository is missing tag of release 4.0.0-beta.2 even though there is such version at npmjs).

> Is the master branch on release v3.0.0? I tried downgrading project to v3 but tests started breaking. 

You should be aware that node-saml versions at npmjs prior to 4.x are NOT from node-saml/node-saml repository. Those are from totally different codebase (see #21 for further information).

One more thing which makes things a bit fuzzy is that when baseline for node-saml/node-saml was created (by forking node-saml/passport-saml version 3.0.0) someone introduced also release tags from passport-saml repository to node-saml repository even though node-saml/node-saml has not had any releases prior to 4.x betas (someone might get an idea that these releases https://github.com/node-saml/node-saml/tags  would all be from node-saml/node-saml)
Ping @cjbarth @markstos

**Pull request closed without merging**
